### ISSUE TITLE
[v3] Scheduling is broken, card is always moved to 1

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading#46]
Anki 2.0.47 (v4 on Anki 2.1.0 beta 26 seems to work, and the first card is different). I have 3453 cards in my IR deck. The Scheduling settings are 10 and 50 %.  The card is always moved to 1.  The Organizer is too manual and not convenient (certainly not for 10 and 50 %).

**Comment by aleksejrs** [comment]
Also, unlike with v4, scheduling is recorded in the card's history.

**Comment by luoliyan** [comment]
I do remember fixing a lot of issues with scheduling in v4. I'll see how much of that I can backport to v3. I understand that Anki 2.0 isn't going anywhere any time soon.

Thanks.

**Comment by Smingvin** [comment]
New user here (a couple of days), Anki 2.0.41, ir cards always moved to 1 regardless of what I click.

**Comment by Smingvin** [comment]
I tested the scheduler a bit. This is what happens:

Settings: percentage, randomize.

1. Any percentage between 0 and 99 will return the card to position 1. 
2. If you set percentage to 100, cards will be moved at or near the bottom of the pile.
3. If you set percentage to above 100 (either 150 or 1000) the cards will be moved to the bottom, while the tooltip will report an proportionate but non-existing index (for example: "card is moved to position 350", even though the deck has 50 cards so it is actually moved to 50)

I hope this information will be helpful for debugging.

**Comment by SijanC147** [comment]
I'm not sure if there are any other issues, with the scheduler, but the problem that @Smingvin mentions, in particular, is due to the way that python 2 deals with the division of integer values, which are not automatically cast to float, this can be solved one of two ways, both in scheduler.py, 

Either change the following line, (which was resulting in 0 every time due to loss of precision): 
````python 
    newPos = totalCards * (value / 100)
````
to 
````python 
    newPos = totalCards * (float(value) / 100)
````

or, the preferred way is to import the more robust division, by changing the very first line to 

````python
from __future__ import unicode_literals, division
````

**Comment by luoliyan** [comment]
@SijanC147, thanks so much for that. I've made the suggested change. Hopefully this resolves the main issue here.
