### ISSUE TITLE
Config menu in Anki 2.1?

### ISSUE THREAD

**Issue by njm2112** [luoliyan/incremental-reading#72]
It doesn't appear that the configuration options are available for the IR3 add-on in Anki 2.1 (beta 36).

The 'Read' menu doesn't show any choice to set config options, nor to modify keyboard shortcuts.

The Tools > Add-ons menu has a button for 'Config options' but when selecting 'Incremental Reading' in the list and then pressing the 'Config options' button, Anki returns the error 'Add-on has no configuration.' (This happens for all add-ons though, so might not be specific to accessing IR's options through the Add-ons menu.)

What am I missing here?

**Comment by luoliyan** [comment]
Many add-ons don't have a config file and haven't registered a config dialogue with Anki, so that doesn't necessarily indicate a general problem with your installation. However, if the "Read" menu is missing "Options...", that's not something I can explain. What happens when you press <kbd>Alt</kbd>+<kbd>1</kbd>?
