### ISSUE TITLE
Not a feature request, just a question...

### ISSUE THREAD

**Issue by p2635** [luoliyan/incremental-reading#78]
I'm really interested in this add on but.. there are no instructions. Can someone please teach me how to use it?? If someone can just show me the way, I might even make a youtube video on how to use it to help others like me.

**Comment by aleksejrs** [comment]
Manual for the previous version (the service used in a link at AnkiWeb can't show the page for me): https://github.com/aleksejrs/anki-2.0-vsa-and-ire/blob/for_everyone/doc/View_Size_Adjust_and_Incremental_Reading_Extension_addons_-_Google_Groups.html

**Comment by p2635** [comment]
Thanks @aleksejrs. I read through some of it and I understand the features now.

The problem is, there isn't like a step by step guide on how to actually use this in the real world. It would be good to get specific examples of how everyone uses it.
For example:
1. What kinds of articles do you use IR  for?
2. How many articles (cards) do you keep in your 'organiser' queue at any given time?
3. What is the difference between highlighting and extracting? (aren't they the same?) 
4.  If you're just extracting the most important parts of the article (into individual cards), what is the point of keeping it in the organiser?

**Comment by aleksejrs** [comment]
I don't use it much, especially now that I have v3 and v4 installed and v3 (for Anki 2.0) was broken, but also because I had many useless extracts and didn't know what to do with them. I am unable to use the best learning methods and don't know what to prioritize.  So I have > 1500 IR cards, am adding more and forgetting about them.

1. As an article on IR at supermemo.com says, Wikipedia articles may be good for IR because (something like) they are written by many people and there is not much context to hold in your head to be able to understand a sentence. Also when I needed to read Terms of Service or similar, IR worked.

2. There is no bottom limit. The top limit depends on your ability to prioritize them. Somebody added a different mode for that, but mode switching has a dangerous bug with filtered decks (I use them to prioritize everything): issue #76.

3. Highlighting does not create new cards.

4. After you have extracted all the important parts, you can delete the original article.

**Comment by p2635** [comment]
Thanks again. I just have 1 more question. For number 3, my question was really 'What is the usefulness highlighting vs extracting?'.

**Comment by aleksejrs** [comment]
I use it to discard useless parts that are not clearly worth deleting (and I think there was no "delete" in v2).

**Comment by p2635** [comment]
Thanks, I'm gonna close this now.
